name: Deploy to SSH Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v3

      - name: Деплой на сервер
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd "/home/nnbdx99/Effective Mobile_Block5"
            git pull origin master
            composer install --no-dev
            php artisan migrate --force
            sudo systemctl restart php-fpm

#name: Deploy on push to master
#
#on:
#  push:
#    branches:
#      - master
#
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Set up SSH
#        uses: webfactory/ssh-agent@v0.5.3
#        with:
#          ssh-private-key: ${{ secrets.SSH_KEY }}
#
#      - name: Деплой на сервер
#        uses: appleboy/ssh-action@v0.1.7
#        with:
#          username: ${{ secrets.SSH_USER }}
#          key: ${{ secrets.SSH_KEY }}
#          script: |
#            cd '/home/nnbdx99/Effective Mobile_Block5'
#            git pull origin master
#            composer install --no-dev
#            php artisan migrate --force
#            sudo systemctl restart php-fpm